export const GET_EMPLOYEES_REQUESTED = 'GET_EMPLOYEES_REQUESTED';
export const GET_EMPLOYEES_SUCCESS = 'GET_EMPLOYEES_SUCCESS';
export const GET_EMPLOYEES_FAILD = 'GET_EMPLOYEES_FAILD';
export const POST_EMPLOYEE_REQUESTED = 'POST_EMPLOYEE_REQUESTED';
export const POST_EMPLOYEE_SUCCESS = 'POST_EMPLOYEE_SUCCESS';
export const POST_EMPLOYEE_FAILD = 'POST_EMPLOYEE_FAILD';
export const DELETE_EMPLOYEE_REQUESTED = 'DELETE_EMPLOYEE_REQUESTED';
export const DELETE_EMPLOYEE_SUCCESS = 'DELETE_EMPLOYEE_SUCCESS';
export const DELETE_EMPLOYEE_FAILD = 'DELETE_EMPLOYEE_FAILD';
export const UPDATE_EMPLOYEE_REQUESTED = 'UPDATE_EMPLOYEE_REQUESTED';
export const UPDATE_EMPLOYEE_SUCCESS = 'UPDATE_EMPLOYEE_SUCCESS';
export const UPDATE_EMPLOYEE_FAILD = 'UPDATE_EMPLOYEE_FAILD';
export const SET_EMPLOYEE_EMPTY = 'SET_EMPLOYEE_EMPTY';
export const SET_ERROR_MESSAGE_EMPTY = 'SET_ERROR_MESSAGE_EMPTY';
export const SET_EDIT_EMPLOYEE = 'SET_EDIT_EMPLOYEE';




